- v3.1/Dockerfile
- v3.1/entrypoint.sh
Adds an entrypoint script to ensure some folders exist when volumes are mounted over those locations.
Note that the script calls the base image's entrypoint script. It's a pain. :worried:
> Add entrypoint to ensure folders in mounted volumes

- v3.1/Dockerfile
We need to re-add the upstream CMD in our Dockerfile.
Why? Docker assumes that we want change the entrypoint + command logic when we override the ENTRYPOINT, and clears the CMD silently. (Hint: Verify this with `docker inspect vshn/modsecurity`)
> Add upstream command (stripped out by Docker)

- v3.1/sites-available/000-default.conf
These changes
- add a `/healthz` endpoint to the Apache configuration,
- which does not log any access to it.
The endpoint is implemented using Apache's [mod_status](https://httpd.apache.org/docs/2.4/mod/mod_status.html) module. Note that that page also mentions having `mod_status` loaded (which is the default in the base image) is considered a security risk.
> Add non-logging /healthz endpoint

- v3.1/custom-rules/after-crs.dist/cleanlogs.conf
Adds an ignore rule to avoid logging requests in the audit.log on the `/healthz` endpoint to the default configuration.
Without this rule any access to `/healthz` is logged in the Apache `ErrorLog` and `/var/log/modsecurity/audit.log` (as currently the case).
Thanks to @franbuehler to pair programming! :medal_sports:
> Add ignore rule for /healthz to keep log clean

- v3.1/Dockerfile
- v3.1/transform-alert-message.awk
The awk installed in the base image is not compatible with GNU awk. That makes the `transform-alert-message.awk` script fail.
> Install and use gawk for transform script

- v3.1/Dockerfile
- v3.1/custom-rules/after-crs.dist/cleanlogs.conf
We need to use `allow` instead of `pass` to make ModSecurity stop processing.
> Stop processing rules on /healthz URI path

- v3.1/Dockerfile
Since we upgraded the base image last week bringing up a pod on OpenShift fails:
```
Could not open configuration file /etc/modsecurity.d/modsecurity.conf: Permission denied
```
Some configuration files in `/etc/modsecurity.d/` have permissions 700 and all of them belong to `root`. Since OpenShift uses an arbitrary (non-root) user Apache can access those files.
The fix applies the [typical OpenShift user permission](https://docs.okd.io/latest/creating_images/guidelines.html#openshift-specific-guidelines) also to the `/etc/modsecurity.d/` folder.
> Fix permission issues for /etc/modsecurity.d

- v3.1/custom-rules/after-crs.dist/infrastructure.conf
OpenShift 3 routers add a specific Forwarded request header that triggers 920274 on PL4.
This PR excludes the mentioned request header from the rule 920274.
> Add generic infrastructure exclusion rule for OpenShift

- v3.1/custom-rules/before-crs.dist/geolocation.conf
In order to reduce the log output regarding a missing LookupDB we commented out the two rules which are affected
> Comment out two rules regarding the geoLookupDB

- v3.1/Dockerfile
- v3.1/sites-available/000-default.conf
1) Add mod_status support for use with apache_exporter
2) Add another access log file location for parsing metrics 
from the access log.
Open for discussions if another CustomLog directive with "/dev/null" is a good approach. Haven't found a better solution.
> Add metrics supports

- v3.1/custom-rules/before-crs.dist/cleanlogs.conf
Suppresses log entries that are coming from localhost,
e.g. a sidecar like the Apache exporter.
I'm not sure what `ctl:ruleRemoveById=920300` does, please indicate whether this is correct.
> Add rule to ignore requests from localhost

- README.md
- v3.1/Dockerfile
- v3.1/clamd.conf.template
- v3.1/entrypoint.sh
- v3.1/virus-check.pl
It's now possible to scan uploaded files for viruses via modsecurity.
The script `/opt/virus-check.pl` will scan any uploaded file for
viruses using clamav. The script requires a remote clamd server
listening on port 3310. The clamd server can be specified using the
ENV variables `$CLAMD_SERVER` and `$CLAMD_PORT`.
> Add support for clamav virus scan

- README.md
- v3.1/Dockerfile
- v3.1/virus-check.pl
Log ClamAV scanning debug logs to stdout and make it configurable.
> Configure ClamAV scanning logs

- v3.1/modsecurity.d/include.conf
Makes sure we can apply (exclusion) rule _before_ any rules of the CRS are included.
**Relates to:** [FILO-255](https://control.vshn.net/tickets/FILO-255)
> Include crs-setup rules *after* before-crs rules

- v3.1/modsecurity.d/include.conf
This enables the configuration of recommended rules.
> Move custom before-crs rules as first import

- v3.1/conf-available/logging.conf
`%O` and `%I` provide the timing metrics. `%D` replaces `%b` to log the full size of the response (including headers).
> Add timing information for metrics log

- .github/workflows/test.yml
- v3.1/.dockerignore
- v3.1/Dockerfile
- v3.1/custom-rules/before-crs.dist/baseconfig.conf
- Fixes quoting issue (introduced with #43)
- Adds a smoke test for PRs
- Makes `grep` extract additional settings from example `crs-setup.conf`
> Add GitHub action to test PRs

- v3.3/Dockerfile
We need write permissions on the owasp-crs folder for modsecurity to
work properly.
> Add correct permissions for owasp-crs folder

- v3.3/Dockerfile
A security fix released in CVE-2021-35368 has been published and this
image is updated to the latest version that fixes the issues in that CVE
> fix(security): Update to version 3.3.2

- renovate.json
The new tags contain the build date of the Docker image. This makes it incompatible with the default versioning strategy of Renovate.
The current setup is based on the CRS minor version and automerging patch updates is therefore acceptable.
Renovate treats build number updates as patch updates.
> Integrate modsecurity-crs' new tag strategy

- v3.3/Dockerfile
Further, this introduces the new tag strategy of the dependency
which Renovate knows with #101.
> Update ModSecurity CRS to 3.3.4

- renovate.json
The dockerfile was updated to use the fully qualified path for the docker image some time ago.
> deps: Ensure Renovate config matches ModSec image

- v3.3/transform-alert-message.awk
The PCRE error messages have slightly different format (no whitespace between the different fields inclosed in square brackets)
This leads to parsing issues in the awk script, as it doesn't recognize the fields correctly anymore due to the missing whitespace.
By adjusting the input so that between a closing and opening square braken there always is a whitespace, we ensure that the fields are correctly distinguished.
Resolves: #45
> Fix parsing issues for PCRE error messages

- v3.3/custom-rules/before-crs.dist/baseconfig.conf
- v3.3/httpd-logging.conf
- v3.3/modsecurity.d/include.conf
The anomaly score variables are not set to a specific value at the beginning. This can lead to an empty field in the access-log if a rule is triggered with a `deny`. The reason is, that a deny will abort any further rule evaluation and therefore also the anomaly score calculation. Initializing the scores to 0 at the beginning eliminates this issue.
> Set initial value for in- and outbound anomaly score

- .github/workflows/push.yml
Changes:
- Replaces docker build in push workflow with docker/build-push-action@v5
> Replace quay.io with ghcr.io

- transform-alert-message.awk
Parsing for uniqueID in awk script for ERRORLOG was broken.
This lead to the resulting json being invalid and therefore unable to be parsed by indexer.
Example:
Raw output:
```
[Tue Sep 17 08: 05: 27.183579 2024
] [security2:error
] [pid 21:tid 50
] [client 172.23.0.1: 37142
] [client 172.23.0.1
] ModSecurity: Warning. Pattern match "(?i)\\\\b(?:(?:alter|(?:(?:cre|trunc|upd)at|renam)e|de(?:lete|sc)|(?:inser|selec)t|load)[\\\\s\\\\x0b]+(?:char|group_concat|load_file)\\\\b[\\\\s\\\\x0b]*\\\\(?|end[\\\\s\\\\x0b]*?\\\\);)|[\\\\s\\\\x0b\\\\(]load_file[\\\\s\\\\x0b]*?\\\\(|[\\"'`
][\\\\s\\\\x0b
]+regexp[^0-9A-Z_a-z
]|[\\"'0-9A- ..." at ARGS:custname. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"
] [line "488"
] [id "942360"
] [msg "Detects concatenated …
```
> Fix awk script parsing of ERRORLOG for key uniqueID

- Dockerfile
- transform-alert-message.awk
Adjust log output in order to avoid race condition in which separate log outputs get written to same line rendering them unable to be parsed by log collectors.
> Adjust log output
